language: java
jdk: oraclejdk8

script: mvn package

deploy:
  provider: releases
  api_key: 
    secure: 930a37b459f892bb170632a9ed3b719ed3cb4b90

  #api_key: ${GH_TOKEN}
  #composer: config github-oauth.github.com ${GH_TOKEN}
  file: "/home/travis/build/agian75/AcademicManagerMvm/target/AcademicManagerMaven-0.0.1-SNAPSHOT.war"
  skip_cleanup: true
  on:
    tags: true
