language: java
jdk: oraclejdk8

script: mvn package

deploy:
  provider: releases
  api_key: 
      secure: hZxvu1AktxYGuSxJjZd2M23dO4rdeSX2u3BHhLdhji4kCI+Fkg8Ksk08UCYfi/NGT9H/ZJ4Gd/xXNiZHArXS/UHAyUF5AXmoyOZRCUUFIBQE8xGykp9cYlgHsGp/8+1yJygAWQcTAzQsghHntVgcAJqvMpuZ/Z3/jNlUaeVZkCRz+/onmuF1YxQ3P5B+5qjkKyPPXKMEerGOR3zDIMbgyRFPpvTRSj6EvoQUaohie1/8sIk2tYJzo5xy2yIwaMn4SoSj7jjYaBBJU2AYfGB/PGCirPhni2REMKg68aYz0trIaR2K12RTDaw4Uj4V99lVDYTxs/Uaw2jWP2Bqf0aSlKOXmO9vqv2slYkrQGIvFTqGIEtti5E95uM665y063TQuQmKsM+QMol8HzLrdlOSiQROsYghJuG6Kl8HN1K3mxQqrfPs+aDAb0chB7WsB2sRbgLXSOkbeLWfUZI8jwj6LeZCm71QRNgGlQ1C+6SUo5dlZDRsEKnLIl44CQCE+3tFsTXUj0yhiksYn1WQEHRXxLH3vyggYkYCfzrZEOSaPIg36S1CW3ENt0BlAAugmS23nHZz+dpHp6cH5n/cseOYH3Ci7/A5TcfnMVaR/UqUDsk8SeRIJ7TBGIgb9/wq67CVd1NV3s0dyriHSXI+XZKCC5ETsV/662U555amqZHPxuU=

  file: "/home/travis/build/agian75/AcademicManagerMvm/target/AcademicManagerMaven-0.0.1-SNAPSHOT.war"
  skip_cleanup: true
  on:
    tags: true
