language: java
jdk: oraclejdk8

script: mvn package

deploy:
  provider: releases
  api_key: 
    secure: "20b54b31d6dfa437f7724410d02467b8c7d87e54"
  file: "AcademicManagerMaven-0.0.1-SNAPSHOT.war"
  skip_cleanup: true
  on:
    tags: true
