language: java
jdk: oraclejdk8

script: mvn package

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  #composer: config github-oauth.github.com ${GH_TOKEN}
  file: "AcademicManagerMaven-0.0.1-SNAPSHOT.war"
  skip_cleanup: true
  on:
    tags: true
